version: '3'
services:
  web:
    image: php:7.2-apache
    expose:
      - "80"
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
  database:
    image: mysql:5.7
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./db:/var/lib/mysql
    expose:
      - '3306'
    ports:
      - '3306:3306'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - '8080:80'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      PMA_HOST: 'database'
~
